# -*- coding: utf-8 -*-
"""Lost ferry.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TnBx5AK-xBCdDkN1wm36tUdDrGXcebou
"""

from google.colab import drive
import pandas as pd

drive.mount('/content/drive')

# Load the dataset into a pandas dataframe
df = pd.read_csv('/content/drive/MyDrive/prices-split-adjusted.csv', parse_dates=['date'])

# Find the first and last date in the dataset
first_date = df['date'].min()
last_date = df['date'].max()

print(first_date,last_date)

# Filter the dataframe to only include data between the first and last date
df_filtered = df[df['date'].between(first_date, last_date)]

print(df_filtered)

# Calculate the percentage increase for each stock
df_filtered['percent_increase'] = (df_filtered['close'] - df_filtered['open']) / df_filtered['open'] * 100

print(df_filtered['percent_increase'])

# Sort the dataframe by percent_increase in descending order
df_sorted = df_filtered.sort_values(by='percent_increase', ascending=False)

print(df_sorted )

# Print the top 10 performing stocks
print(df_sorted.head(10))